apiVersion: batch/v1
kind: Job
metadata:
  name: e2e-tests
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: e2e
          image: __E2E_IMAGE__
          env:
            - name: BASE_URL
              value: "http://demo-app:8080"
